### ISSUE TITLE
App CRASH: MultiImageStreamCompleter: Connection refused. Error thrown Instance of 'ErrorDescription'.

### ISSUE THREAD

**Issue by jpetro416** [Baseflow/flutter_cached_network_image#830]
## 🐛 Bug Report
Rapid scrolling produces this crash:
```
new MultiImageStreamCompleter.<fn>
FlutterError - Connection refused. Error thrown Instance of 'ErrorDescription'.
package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:32
```

### Expected behavior
Image url's are fine and work most of the time, rapid scrolling produces this crash

### Reproduction steps
Rapid scrolling produces this crash

### Configuration

**Version:** 
cached_network_image: ^3.2.3

**Platform:** 
- [x ] :iphone: iOS
- [ ] :robot: Android

**Comment by macy11** [comment]
same error I think 

Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Software caused connection abort. Error thrown Instance of 'ErrorDescription'.
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:120)
       at FirebaseCrashlytics.recordFlutterError(firebase_crashlytics.dart:144)
       at FirebaseCrashlytics.recordFlutterFatalError(firebase_crashlytics.dart:157)
       at FlutterError.reportError(assertions.dart:1177)
       at ImageStreamCompleter.reportError(image_stream.dart:728)
       at new MultiImageStreamCompleter.<fn>(multi_image_stream_completer.dart:32)

**Comment by prilepskiy** [comment]
same in Flutter 3.7.10 with cached_network_image 3.2.3:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Connection reset by peer. Error thrown Instance of 'ErrorDescription'.
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:120)
       at FirebaseCrashlytics.recordFlutterError(firebase_crashlytics.dart:146)
       at FirebaseCrashlytics.recordFlutterFatalError(firebase_crashlytics.dart:159)
       at main.<fn>(main.dart:28)
       at FlutterError.reportError(assertions.dart:1189)
       at ImageStreamCompleter.reportError(image_stream.dart:738)
       at new MultiImageStreamCompleter.<fn>(multi_image_stream_completer.dart:32)
       at _SuspendState._createAsyncStarCallback.<fn>(dart:async)
       at new MultiImageStreamCompleter.<fn>(multi_image_stream_completer.dart:25)
```

**Comment by chuiizeet** [comment]
Flutter 3.7.6 with cached_network_image 3.2.3:
```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: HandshakeException: Connection terminated during handshake. Error thrown Instance of 'ErrorDescription'.
       at FirebaseCrashlytics.recordError(firebase_crashlytics.dart:120)
       at FirebaseCrashlytics.recordFlutterError(firebase_crashlytics.dart:146)
       at FlutterError.reportError(assertions.dart:1189)
       at ImageStreamCompleter.reportError(image_stream.dart:738)
       at new MultiImageStreamCompleter.<fn>(multi_image_stream_completer.dart:32)
       at _SuspendState._createAsyncStarCallback.<fn>(dart:async)
       at new MultiImageStreamCompleter.<fn>(multi_image_stream_completer.dart:25)
```

**Comment by LatCui** [comment]
have the same issue

**Comment by meg4cyberc4t** [comment]
have the same issue

**Comment by ye-ha** [comment]
I also faced the same issue.

**Comment by mdmota** [comment]
waiting too

**Comment by sajaadem** [comment]
I am also facing this issue

**Comment by jpetro416** [comment]
⚠️We are all waiting @renefloor  `cached_network_image: 3.2.3`

Everyone else: This is a critical bug, and I have removed this package from my project and instead used this basic code below as a workaround, which surprisingly does NOT crash the app.



```

Widget displayImage(String picUrl, double size) {
  return Image.network(
    picUrl,
    width: size,
    height: size,
    fit: BoxFit.cover,
    errorBuilder: (context, error, stackTrace) {
      print(error);
      return _getFlatPlaceholderOrErrorImage(size, false);
    },
    loadingBuilder: (context, Widget child, ImageChunkEvent? loadingProgress) {
      if (loadingProgress == null) return child;
      return Center(
        child: new CircularProgressIndicator(backgroundColor: Colors.white,),
      );
    },
  );
}
```

**Comment by jpetro416** [comment]
Same issue posted here as well: 
https://github.com/Baseflow/flutter_cached_network_image/issues/859

**Comment by sajaadem** [comment]
@jpetro416 version 3.2.3 is already published but the issue still exist ...

**Comment by tomquas** [comment]
i am seeing this crash on ios in production, not debug.
there has been discussion [here](https://github.com/flutter/flutter/issues/112706) and [here](https://github.com/flutter/flutter/issues/116756) but nobody seemed to really solved it yet.
<details>
<summary>$ flutter doctor</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.6, on macOS 13.5 22G74 darwin-arm64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.80.2)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
</details

**Comment by MaximilianFlechtner** [comment]
+1

**Comment by AshishDoubleDotts** [comment]
have the same issue

**Comment by iballan** [comment]
Same issue here:
```
new MultiImageStreamCompleter.<fn>
FlutterError - Operation timed out. Error thrown resolving an image codec.
package:cached_network_image/src/image_provider/multi_image_stream_completer.dart:32
```
and in the details:
```
Fatal Exception: FlutterError
ClientException: Connection closed before full header was received, uri=https://www.gstatic.com/webp/gallery/1.webp. Error thrown resolving an image codec.
```

**Comment by gvozditskiy** [comment]
We also have a lot of this bugs in production on Android

**Comment by iballan** [comment]
What I'm testing now is this:
In my pubspec.yaml: 
Instead of cached_network_image: I imported this from my repo:
```yaml
  cached_network_image: # Temporary until they fix it here
    git:
      url: https://github.com/iballan/flutter_cached_network_image
      path: cached_network_image
      ref: develop
```

I added error listener to the image:

```dart
return CachedNetworkImage(
      imageUrl: url ?? Constants.defaultImageUrl,
      fit: fit,
      width: width,
      height: height,
      progressIndicatorBuilder: (context, url, downloadProgress) => LoadingIndicator(),
      errorListener: (error) {
        Timber.w('Error loading image: $error'); // <- this is the listener
      },
      errorWidget: (context, url, error) => Center(
        child: ErrorWidget(width: width, height: height),
      ),
    );
```
The change I've done on the original repo is [this commit: Link](https://github.com/iballan/flutter_cached_network_image/commit/3ea0fdf419857e382638fa87220bc0c6c570fd2b)
When there is an error, instead of rethrowing, i just call the errorListener:
```dart
      if (errorListener != null) {
        errorListener(e);
      } else {
        rethrow;
      }
```

I'm hoping that this fixed it. Otherwise i will have to remove more error handling and suppress error more in this library!

I'm not sure why even though on top of errorListener, and errorWidget the error is thrown out !? Why would that be the case? I don't think anybody want to crash the app if the image didn't load tho

**Comment by iballan** [comment]
I released an update with the fix above and until now it looks like the issue didn't appear on the latest version!

**Comment by iballan** [comment]
Yess, after the fix above I can say that it was fixed for me! I don't see related crash reports anymore!

**Comment by YonatanSegura97** [comment]
Any solution?, My Crashlytics dashboard shows a lot of exceptions. Please provide a solution.

**Comment by jpetro416** [comment]
Will someone patch this? I don't use the package anymore, but this package needs this patch

**Comment by maxAtIppen** [comment]
I still have the same issue.

Versions:

Flutter 3.24.2
flutter_cached_network_image 3.3.1

From Crashlytics:

ClientException with SocketException: Software caused connection abort (OS Error: Software caused connection abort, errno = 103),

new MultiImageStreamCompleter.<fn> (multi_image_stream_completer.dart:26)

**Comment by dinhtuquyen** [comment]
I still have the same issue
Flutter 3.24.3
flutter_cached_network_image 3.3.1

**Comment by mbfakourii** [comment]
@renefloor 

I still have the same issue

**Comment by jpetro416** [comment]
I still have this issue, how is this not resolved?

**Comment by unix14** [comment]
anything?
